name: Python application test with Github Actions using devcontainers

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        make install
        make lint
        make format
